### ISSUE TITLE
Document new statuses / statusCodes for OTAResponse

### ISSUE THREAD

**Issue by bettio** [edgehog-device-manager/edgehog-astarte-interfaces#55]
New statuses and statusCodes have been introduced.

statuses:
- Acknowledged
- Downloading
- Deploying
- Deployed
- Rebooting
- Success
- Error

Also following status codes are known:
- UpdateAlreadyInProgress
- NetworkError
- IOError
- InternalError
- InvalidBaseImage
- SystemRollback
- Cancelled

Let's allow sending a string with the internal error message, using a message endpoint.

**Comment by harlem88** [comment]
Add `InvalidRequest` to status codes to handle if a request contains incorrect data or malformed json etc.
